//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjustment
    {
        public int ID { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public string AdjustmentType { get; set; }
        public string Type { get; set; }
        public Nullable<int> UserID { get; set; }
        public decimal Amount { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTimeStamp { get; set; }
        public string Description { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckOutRequest
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Status { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int Id { get; set; }
        public string KeyName { get; set; }
        public string KeyValue { get; set; }
        public bool IsActive { get; set; }
    }
}
namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ledger
    {
        public int ID { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public string AdjustmentType { get; set; }
        public string Type { get; set; }
        public Nullable<int> UserID { get; set; }
        public decimal Amount { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTimeStamp { get; set; }
        public decimal Balance { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public string LogMessage { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string AddedBy { get; set; }
    }
}
namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Page()
        {
            this.UserPages = new HashSet<UserPage>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string URL { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int SortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPage> UserPages { get; set; }
    }
}
namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductLevels = new HashSet<ProductLevel>();
            this.UserSales = new HashSet<UserSale>();
            this.UserProducts = new HashSet<UserProduct>();
            this.UserRequests = new HashSet<UserRequest>();
        }
    
        public int ID { get; set; }
        public string ProductName { get; set; }
        public string ImagePath { get; set; }
        public Nullable<decimal> ConsumePrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> FinalSalePrice { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductLevel> ProductLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSale> UserSales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProduct> UserProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRequest> UserRequests { get; set; }
    }
}
namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLevel
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int LevelNumber { get; set; }
        public decimal Percentage { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesComissionNthLevel
    {
        public int ID { get; set; }
        public Nullable<int> UserSaleID { get; set; }
        public Nullable<int> BeneficierUserID { get; set; }
        public Nullable<decimal> ComissionPercentage { get; set; }
        public Nullable<decimal> ComissionAmount { get; set; }
        public string Status { get; set; }
        public bool IsCheckOut { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
    
        public virtual UserSale UserSale { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdiagram
    {
        public string name { get; set; }
        public int principal_id { get; set; }
        public int diagram_id { get; set; }
        public Nullable<int> version { get; set; }
        public byte[] definition { get; set; }
    }
}
namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserDetail()
        {
            this.CheckOutRequests = new HashSet<CheckOutRequest>();
            this.Ledgers = new HashSet<Ledger>();
            this.SalesComissionNthLevels = new HashSet<SalesComissionNthLevel>();
            this.UserDetails1 = new HashSet<UserDetail>();
            this.UserNthLevels = new HashSet<UserNthLevel>();
            this.UserPages = new HashSet<UserPage>();
            this.UserSales = new HashSet<UserSale>();
            this.UserSales1 = new HashSet<UserSale>();
            this.UserSales2 = new HashSet<UserSale>();
            this.UserProducts = new HashSet<UserProduct>();
            this.Adjustments = new HashSet<Adjustment>();
            this.UserRequests = new HashSet<UserRequest>();
        }
    
        public int ID { get; set; }
        public string AccountNumber { get; set; }
        public string ImagePath { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserType { get; set; }
        public string ContactNo { get; set; }
        public string ContactNo2 { get; set; }
        public string CNIC { get; set; }
        public string FatherName { get; set; }
        public string Education { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ReferrerID { get; set; }
        public Nullable<decimal> PercentageOfSale { get; set; }
        public Nullable<int> ComissionUptoLevel { get; set; }
        public bool IsSuperAdmin { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string CurrentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public Nullable<int> ParentAccountID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckOutRequest> CheckOutRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ledger> Ledgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesComissionNthLevel> SalesComissionNthLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserDetail> UserDetails1 { get; set; }
        public virtual UserDetail UserDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserNthLevel> UserNthLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPage> UserPages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSale> UserSales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSale> UserSales1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSale> UserSales2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProduct> UserProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adjustment> Adjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRequest> UserRequests { get; set; }
    }
}
namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNthLevel
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int LevelNumber { get; set; }
        public decimal Percentage { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPage
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PageID { get; set; }
        public Nullable<bool> IsAllowed { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProduct
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRequest
    {
        public int ID { get; set; }
        public int RequestByUserID { get; set; }
        public string RequestType { get; set; }
        public string RequestTitle { get; set; }
        public string RequestDescription { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Status { get; set; }
        public string TransactionID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
namespace Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserSale()
        {
            this.SalesComissionNthLevels = new HashSet<SalesComissionNthLevel>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public string SalesNo { get; set; }
        public Nullable<int> ReferredUserID { get; set; }
        public Nullable<int> SaleProductID { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> ComissionAmount { get; set; }
        public string Status { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> ComissionPercentage { get; set; }
    
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesComissionNthLevel> SalesComissionNthLevels { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual UserDetail UserDetail1 { get; set; }
        public virtual UserDetail UserDetail2 { get; set; }
    }
}
